name: Format, Lint, Build, Specs

on:
  pull_request:
  workflow_dispatch:

env:
  CI_IMAGE: ghcr.io/neuralegion/ci_basic_image:v38

jobs:
  check_format:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container:
      image: ghcr.io/neuralegion/ci_basic_image:v38
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Format check
        run: crystal tool format --check

  run_specs:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container:
      image: ghcr.io/neuralegion/ci_basic_image:v38
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install shards
        run: shards install
      - name: Run specs
        run: crystal spec spec/
